name: survey-write

services:
  spoa:
    container_name: spoa
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: uv run python ./docker/sample_server.py
    networks:
      spoe:
        ipv4_address: 172.16.0.10

  haproxy:
    image: haproxy
    container_name: haproxy
    ports:
      - "8080:80"
    volumes:
      - "./haproxy_configs:/usr/local/etc/haproxy"
    networks:
      - spoe

  whoami:
    image: traefik/whoami
    container_name: whoami
    command:
       - --port=8000
       - --name=iamfoo
    networks:
      spoe:
        ipv4_address: 172.16.0.11


networks:
  spoe:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
